language: r
cache: packages
sudo: true

notifications:
  email:
    recipients:
     - alerts+diagram@gmail.com
    on_success: change
    on_failure: change

r:
  - release

apt_packages:
  - libglpk-dev

bioc_packages:
  - graph
  - grBase

r_binary_packages:
  - shiny
  - dplyr

before_script:
    - Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/gRain/gRain_1.3-0.tar.gz", repos=NULL, type="source")''


r_github_packages: AnalytixWare/ShinySky

