language: r
cache: packages

notifications:
  email:
    recipients:
     - alerts+diagram@gmail.com
    on_success: change
    on_failure: change

# Annoying bug with Rcpp and R4.0.0 just now.
# Should be fiexed soonish
jobs:
  include:
    - r: oldrel
      repos:
        CRAN: https://packagemanager.rstudio.com/all/__linux__/xenial/latest
    - r: release
    - r: devel
      repos:
        CRAN: https://packagemanager.rstudio.com/all/__linux__/xenial/latest

apt_packages:
  - libglpk-dev
  - libnode-dev

# Bioconductor bug - should be fixed soonish
# https://travis-ci.community/t/in-r-version-4-0-0-library-path-not-writable/9744/15
bioc_required: false
before_install:
    - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site
    - Rscript -e 'install.packages("BiocManager")'
    - Rscript -e 'BiocManager::install(c("graph", "gRBase", "RBGL", "Rgraphviz"))'

# gRain is installed then we need to install on top
before_script:
    - Rscript -e 'install.packages("functional")' # for gRain 1.3-0
    - Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/gRain/gRain_1.3-0.tar.gz", repos=NULL, type="source")'

r_github_packages: AnalytixWare/ShinySky

# Delete this when R package passes with no warnings
script:
  - R CMD build .

#after_success:
#  - Rscript -e "if (Sys.getenv('TRAVIS_R_VERSION_STRING') == 'release') source('deploy_to_shinyapps.R')"


